# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
 
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
         version: 12 

    - name : GitHub Actions for Yarn  
      uses: Borales/action-yarn@v2.1.0
      with: 
        cmd: install
    
    - name: installing surge
      run: npn install -g surge
    - name: creating build 
      run: yarn build
      
    - name: deploying on surge
      run: surge ./build http://siraj-application.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
            
      
